/**
 * Internal schema for ATOM UIKit registry items.
 * This is the authoring format — build-registry.mjs compiles it
 * to shadcn-compatible registry-item.json for public consumption.
 */

export type ItemKind = 'component' | 'foundation' | 'hook';

export type Framework = 'react' | 'astro' | 'css';

export type InstallGroup = 'components' | 'styles' | 'foundations';

export interface AtomRegistryItem {
  /** Unique identifier, used as filename: public/r/{name}.json */
  name: string;

  /** What this item is */
  kind: ItemKind;

  /** Primary framework (determines which source files to include) */
  framework: Framework;

  /** Where the CLI writes files in the consumer project */
  installGroup: InstallGroup;

  /** Human-readable name */
  title: string;

  /** Short description */
  description: string;

  /** Other registry items that must be installed first */
  registryDependencies?: string[];

  /** npm packages to install (e.g. "clsx", "gsap") */
  dependencies?: string[];

  /** Source files to include */
  files: AtomRegistryFile[];
}

export interface AtomRegistryFile {
  /** Path relative to monorepo root (source location) */
  sourcePath: string;

  /** Path relative to consumer project root (where CLI writes) */
  outputPath: string;

  /** shadcn file type for CLI routing */
  type: 'registry:component' | 'registry:file';
}

/**
 * The public output format (shadcn-compatible registry-item.json).
 * Generated by build-registry.mjs — never authored manually.
 */
export interface RegistryItemOutput {
  $schema: string;
  name: string;
  type: 'registry:component' | 'registry:file';
  title: string;
  description: string;
  registryDependencies?: string[];
  dependencies?: string[];
  files: Array<{
    path: string;
    type: 'registry:component' | 'registry:file';
    content: string;
  }>;
}
